port:               4567
phone_number:       425-802-8620
api_key:
secret_key:
registration_id_1:  80751514
registration_id_2:  80751515
tokens_file:        tokens
FQDN:               https://api.att.com
